# Travis CI script
language: c

cache: ccache

sudo: false

# Set CI_TIME=true to enable build-step profiling in Travis
# Set CI_TRACE=true to enable shell script tracing in Travis
# Set CI_CONFIG_QUIET=true to enable "configure --quiet" (only report stderr)
env:
  global:
    - CI_TIME=true
    - CI_TRACE=false
    - CI_CONFIG_QUIET=true
  matrix:
    - BUILD_TYPE=default
    - BUILD_TYPE=check_zproject

services:
- docker

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/home:/zeromq:/git-draft/xUbuntu_12.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/home:/zeromq:/git-draft/xUbuntu_12.04/Release.key'
    packages:
    - generator-scripting-language

script:
- ./ci_build.sh
